import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:csv/csv.dart';
import 'package:path_provider/path_provider.dart';
import '../models.dart';

class ReportService {
  static Future<File> generateCSV(List<Expense> expenses, String currency) async {
    List<List<dynamic>> rows = [];
    rows.add(['ID', 'Merchant', 'Date', 'Amount', 'Currency', 'Category']);

    for (var e in expenses) {
      rows.add([e.id, e.merchant, e.date, e.amount, e.currency, e.category]);
    }

    String csvData = const ListToCsvConverter().convert(rows);
    final directory = await getTemporaryDirectory();
    final file = File('${directory.path}/expense_report_${DateTime.now().millisecondsSinceEpoch}.csv');
    return await file.writeAsString(csvData);
  }

  static Future<void> generateAndPrintPDF(
    List<Expense> expenses, 
    String currency, 
    double total,
    String userName
  ) async {
    final pdf = pw.Document();
    final font = await PdfGoogleFonts.interRegular();
    final fontBold = await PdfGoogleFonts.interBold();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            pw.Header(
              level: 0,
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('ExpenseIQ Report', style: pw.TextStyle(font: fontBold, fontSize: 24, color: PdfColors.blue900)),
                  pw.Text(DateTime.now().toString().substring(0, 10), style: pw.TextStyle(font: font, fontSize: 12)),
                ],
              ),
            ),
            pw.SizedBox(height: 20),
            pw.Text('User: $userName', style: pw.TextStyle(font: font, fontSize: 14)),
            pw.Text('Base Currency: $currency', style: pw.TextStyle(font: font, fontSize: 14)),
            pw.SizedBox(height: 10),
            pw.Divider(),
            pw.SizedBox(height: 20),
            
            pw.Table(
              border: pw.TableBorder.all(color: PdfColors.grey300),
              children: [
                pw.TableRow(
                  decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                  children: [
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Date', style: pw.TextStyle(font: fontBold))),
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Merchant', style: pw.TextStyle(font: fontBold))),
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Category', style: pw.TextStyle(font: fontBold))),
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('Amount', style: pw.TextStyle(font: fontBold))),
                  ],
                ),
                ...expenses.map((e) => pw.TableRow(
                  children: [
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(e.date, style: pw.TextStyle(font: font))),
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(e.merchant, style: pw.TextStyle(font: font))),
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text(e.category, style: pw.TextStyle(font: font))),
                    pw.Padding(padding: const pw.EdgeInsets.all(8), child: pw.Text('${e.currency} ${e.amount.toStringAsFixed(2)}', style: pw.TextStyle(font: font))),
                  ],
                )),
              ],
            ),
            pw.SizedBox(height: 30),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.end,
              children: [
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 20, vertical: 10),
                  decoration: const pw.BoxDecoration(color: PdfColors.blue700),
                  child: pw.Text(
                    'Total Spent: $total $currency',
                    style: pw.TextStyle(font: fontBold, fontSize: 16, color: PdfColors.white),
                  ),
                ),
              ],
            ),
            pw.Footer(
              padding: const pw.EdgeInsets.only(top: 40),
              trailing: pw.Text('Generated by ExpenseIQ', style: pw.TextStyle(font: font, fontSize: 10, color: PdfColors.grey500)),
            ),
          ];
        },
      ),
    );

    await Printing.layoutPdf(onLayout: (PdfPageFormat format) async => pdf.save());
  }
}
