// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxMIB3-cXgD6AVnyaPbtPtT7EC8kFgVhY',
    appId: '1:238458552267:android:8e86b2cecf5ba2ef1d004e',
    messagingSenderId: '238458552267',
    projectId: 'expense-iq-flutter-app',
    storageBucket: 'expense-iq-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHha467fYMHpOfBQ16D62ifHO1kXNYhYU',
    appId: '1:238458552267:ios:fd85ae83dc0e562f1d004e',
    messagingSenderId: '238458552267',
    projectId: 'expense-iq-flutter-app',
    storageBucket: 'expense-iq-flutter-app.firebasestorage.app',
    iosBundleId: 'com.expenseiq.expenseIqFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD30qdWrqMkaAknDreGv_Yjre6FOgV0zD0',
    appId: '1:238458552267:web:5fed831240ebed481d004e',
    messagingSenderId: '238458552267',
    projectId: 'expense-iq-flutter-app',
    authDomain: 'expense-iq-flutter-app.firebaseapp.com',
    storageBucket: 'expense-iq-flutter-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD30qdWrqMkaAknDreGv_Yjre6FOgV0zD0',
    appId: '1:238458552267:web:5fed831240ebed481d004e',
    messagingSenderId: '238458552267',
    projectId: 'expense-iq-flutter-app',
    authDomain: 'expense-iq-flutter-app.firebaseapp.com',
    storageBucket: 'expense-iq-flutter-app.firebasestorage.app',
  );
}
